==================================================
 test for integer_validator method of the class BaseGeometry
==================================================

This function could be raise error in the follow cases

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

creates an instance of the class BaseGeometry

    >>> bg = BaseGeometry()

    >>> bg.area()
    Traceback (most recent call last):
    ***
    Exception: area() is not implemented

    >>> bg.integer_validator("side", "10")
    Traceback (most recent call last):
    TypeError: side must be an integer

    >>> bg.integer_validator("side", 10.00)
    Traceback (most recent call last):
    TypeError: side must be an integer

    >>> bg.integer_validator("side", 0)
    Traceback (most recent call last):
    ValueError: side must be greater than 0

    >>> bg.integer_validator("side", -10)
    Traceback (most recent call last):
    ValueError: side must be greater than 0

    >>> bg.integer_validator("side", str)
    Traceback (most recent call last):
    TypeError: side must be an integer

    integer_validator method tuple:
    >>> bg.integer_validator("Foo", (1, 2))
    Traceback (most recent call last):
    TypeError: Foo must be an integer

    >>> bg.integer_validator("Foo", {1, 2})
    Traceback (most recent call last):
    TypeError: Foo must be an integer

    >>> bg.integer_validator("foo", None)
    Traceback (most recent call last):
    TypeError: foo must be an integer

    >>> bg.__class__.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 3 required positional arguments: 'self', 'name', and 'value'

    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> bg.integer_validator("Bar", "bar")
    Traceback (most recent call last):
    TypeError: Bar must be an integer

    >>> bg.integer_validator("Bar", True)
    Traceback (most recent call last):
    TypeError: Bar must be an integer

    >>> bg.integer_validator("a", [1])
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> bg.integer_validator("integer", 1, 2)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 4 were given

    >>> bg.integer_validator("integer")
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'
